### ISSUE TITLE
Superset to Elasticsearch connection error

### ISSUE THREAD

**Issue by NavaneethanPS** [preset-io/elasticsearch-dbapi#33]
Hi,

After executing **pip install elasticsearch-dbapi**, I tried connecting from **Apache Superset to Elasticsearch database,** where I got the below error:
_ERROR: {"error": "Connection failed!\n\nThe error message returned was:\nCan't load plugin: sqlalchemy.dialects:elasticsearch.http", "stacktrace": null}._

Couldn't able to figure out the reason for the error.

Could you please help to solve the issue.

Thanks in advance.

Thanks,
Navaneethan.

**Comment by changesforme** [comment]
https://superset.apache.org/docs/databases/elasticsearch

**Comment by changesforme** [comment]
But I met a new mistake，
error：
Miniconda3/envs/superset/lib/python3.6/site-packages/es/baseapi.py", line 224, in elastic_query
    f"Error ({e.error}): {e.info['error']['reason']}"
TypeError: 'NoneType' object is not subscriptable

**Comment by NavaneethanPS** [comment]
Thanks for responding to my issues.

As I mentioned in my earlier post, I had already executed **pip install elasticsearch-dbapi** and when I tried to connect from Apache Superset, getting the below error in Apache Superset:
ERROR: {"error": "Connection failed!\n\nThe error message returned was:\nCan't load plugin: sqlalchemy.dialects:elasticsearch.http", "stacktrace": null}

Can anyone please help to solve this issue.

Thanks in advance.

**Comment by changesforme** [comment]
Did you make the connection?



| |
13311252087
|
|
13311252087@163.com
|
签名由网易邮箱大师定制
On 9/28/2020 21:10，NavaneethanPS<notifications@github.com> wrote：

Thanks for responding to my issues.

As I mentioned in my earlier post, I had already executed pip install elasticsearch-dbapi and when I tried to connect from Apache Superset, getting the below error in Apache Superset:
ERROR: {"error": "Connection failed!\n\nThe error message returned was:\nCan't load plugin: sqlalchemy.dialects:elasticsearch.http", "stacktrace": null}

Can anyone please help to solve this issue.

Thanks in advance.

**Comment by NavaneethanPS** [comment]
No, Still getting the same error. Not sure of the reason for the connection failure as the error message is not clear and descriptive to find the cause of the connection error from Superset to Elasticsearch.

**Comment by changesforme** [comment]
“
        pip install elasticsearch
        pip install elasticsearch-dbapi
”

You need to install both packages first，After installation，will not "sqlalchemy.dialects:elasticsearch.http".




That's the mistake I've come across now

I'm judging now because the ES server has no SQL plug-in installed,

Plans are under way to install an SQL plug-in for ES,

I'm going on vacation,

But I'll see you in eight days.

I think my current error is caused by the fact that ES did not install the SQL plug-in.

If I succeed then, I will tell you ~

| |
13311252087
|
|
13311252087@163.com
|
签名由网易邮箱大师定制
On 9/30/2020 16:06，NavaneethanPS<notifications@github.com> wrote：

No, Still getting the same error. Not sure of the reason for the connection failure as the error message is not clear and descriptive to find the cause of the connection error from Superset to Elasticsearch.
